name: Add-On Build

on:
  workflow_dispatch:

jobs:
  build_win_ac25:
    runs-on: [ windows-2019 ]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Download Development Kit
      run: python archicad-addon/Tools/download_and_unzip.py ${{ secrets.WIN_DEVKIT_AC25 }} archicad-addon/Build
    - name: Generate Project
      run: cmake -B archicad-addon/Build/AC25 -G "Visual Studio 16 2019" -A "x64" -T "v142" -DAC_API_DEVKIT_DIR="archicad-addon/Build/API Development Kit 25.3002" archicad-addon
    - name: Build Debug
      run: cmake --build archicad-addon/Build/AC25 --config Debug
    - name: Build RelWithDebInfo
      run: cmake --build archicad-addon/Build/AC25 --config RelWithDebInfo
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SomeStuff_AddOn AC25 Win
        path: archicad-addon/Build/AC25/RelWithDebInfo/SomeStuff_AddOn_AC25_Win.apx
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: archicad-addon/Build/AC25/RelWithDebInfo/SomeStuff_AddOn_AC25_Win.apx
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
